/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stylized_bazooka_by_jungle_jim_220kb.glb --types 
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-bazooka-by-jungle-jim-220kb-08810c2c43ea4f2081bd6c72bbae823e
Title: Stylized Bazooka By Jungle Jim (220kb)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material_0: THREE.Mesh
    Cube001_Material003_0: THREE.Mesh
    Cube001_Material001_0: THREE.Mesh
    Cube002_Material003_0: THREE.Mesh
    Cube002_Material001_0: THREE.Mesh
    Cube003_Material001_0: THREE.Mesh
    Cylinder_Material_0: THREE.Mesh
    Cylinder_Material001_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhysicalMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/stylized_bazooka_by_jungle_jim_220kb.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[15.856, -9.65, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.801, 6.952, 10.801]}>
          <mesh geometry={nodes.Cube001_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-25.505, -11.128, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.033, 5.813, 9.033]}>
          <mesh geometry={nodes.Cube002_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube002_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0, 15.728, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[16.523, 16.523, 101.619]}>
          <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[-80.299, 41.982, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-9.239, 2.621, 11.732]} />
        <mesh geometry={nodes.Cube003_Material001_0.geometry} material={materials['Material.001']} position={[15.843, -5.012, 0]} rotation={[-Math.PI / 2, 0.464, 0]} scale={[1.139, 0.921, 4.852]} />
      </group>
    </group>
  )
}

useGLTF.preload('/stylized_bazooka_by_jungle_jim_220kb.glb')
